// Mutation key

export const LOAD = 'LOAD'
export const USER = 'USER'
export const TABLE = 'TABLE'
export const COURSE = 'COURSE'
export const ANNOUNCE = 'ANNOUNCE'
export const HOMEWORK = 'HOMEWORK'
export const TEXTBOOK = 'TEXTBOOK'
export const SCORE = 'SCORE'
export const ROLL = 'ROLL'
export const SETTING = 'SETTING'
export const HWFILE = 'HWFILE'
export const NOTIFY = 'NOTIFY'
export const ANNOUNCE_NOTIFY = 'ANNOUNCE_NOTIFY'
export const HOMEWORK_NOTIFY = 'HOMEWORK_NOTIFY'
export const CLEAR = 'CLEAR'
